### PR TITLE
feat: support for custom fetch function

### PR DESCRIPTION
**Pull request by Yiin**
Context: https://github.com/prismicio/prismic-gatsby/pull/424#issuecomment-897988949

## Package

- [x] gatsby-source-prismic
- [ ] gatsby-plugin-prismic-previews

## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

### CODE REVIEW

**Comment by angeloashmore** [comment]
@Yiin Thanks for the updated PR! I moved the default fetch (using `node-fetch`) to the plugins options schema. Otherwise, everything looks good. 👍

I'll publish this shortly.

**Comment by angeloashmore** [comment]
Published in `v4.1.0` 🎉

**Comment by cometkim** [comment]
This was a breaking change and should be v5.0.0 😅

**Comment by angeloashmore** [comment]
Hey @cometkim, this option defaults to the previous implementation (node-fetch). Is this breaking your project?

**Comment by cometkim** [comment]
@angeloashmore Yes it is... This is how I got notified this 🥲 

image
image

**Comment by angeloashmore** [comment]
@cometkim This could be due to invalid plugin options causing the options validation to fail. Can you share your `gatsby-source-prismic` plugin options?

Related issue: https://github.com/prismicio/prismic-gatsby/issues/437

I believe the underlying issue comes from the plugin not correctly stopping after a failed validation.

**Comment by cometkim** [comment]
Here is my config

https://github.com/daangn/websites/blob/1f767ec/_packages/%40karrotmarket/gatsby-theme-prismic/gatsby/gatsby-config.ts#L8-L20

**Pull request merged**
